apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: frontend-role
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: rbac
rules:
  - apiGroups: ['']
    resources: ['configmaps']
    resourceNames: ['frontend-config']
    verbs: ['get', 'watch']
