apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-accounts.yaml
  - backend-role.yaml
  - frontend-role.yaml
  - role-bindings.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: hospital-erp-system
      app.kubernetes.io/managed-by: kustomize
