apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rolebinding
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: rbac
subjects:
  - kind: ServiceAccount
    name: backend-sa
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontend-rolebinding
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: rbac
subjects:
  - kind: ServiceAccount
    name: frontend-sa
roleRef:
  kind: Role
  name: frontend-role
  apiGroup: rbac.authorization.k8s.io
