apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: service-account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: service-account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pgbouncer-sa
  labels:
    app.kubernetes.io/name: pgbouncer
    app.kubernetes.io/component: service-account
