apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hospital-erp-system

resources:
  - db-migrate.yaml
  - db-seed.yaml
  - db-backup-cronjob.yaml
  - db-backup-pvc.yaml

commonLabels:
  app.kubernetes.io/part-of: hospital-erp
  app.kubernetes.io/component: database
