apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hospital-erp-ingress
spec:
  tls:
    - hosts:
        - staging.hospital.example.com
        - api-staging.hospital.example.com
      secretName: hospital-erp-staging-tls
  rules:
    - host: staging.hospital.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
    - host: api-staging.hospital.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3000
