apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-deny.yaml
  - allow-dns.yaml
  - frontend-policy.yaml
  - backend-policy.yaml
  - database-policy.yaml
  - redis-policy.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: hospital-erp-system
      app.kubernetes.io/managed-by: kustomize
