apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - rbac.yaml
  - config.yaml
  - statefulset.yaml
  - service.yaml
  - promtail-rbac.yaml
  - promtail-config.yaml
  - promtail-daemonset.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: hospital-erp-system
      app.kubernetes.io/managed-by: kustomize
