apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-credentials
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: redis
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: redis-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: redis
          app.kubernetes.io/component: credentials
  data:
    - secretKey: REDIS_URL
      remoteRef:
        key: hospital-erp/redis
        property: url
    - secretKey: REDIS_HOST
      remoteRef:
        key: hospital-erp/redis
        property: host
    - secretKey: REDIS_PORT
      remoteRef:
        key: hospital-erp/redis
        property: port
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: hospital-erp/redis
        property: password
