apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secrets
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: backend
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: backend-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: backend
          app.kubernetes.io/component: credentials
  data:
    - secretKey: JWT_ACCESS_SECRET
      remoteRef:
        key: hospital-erp/backend
        property: jwt_access_secret
    - secretKey: JWT_REFRESH_SECRET
      remoteRef:
        key: hospital-erp/backend
        property: jwt_refresh_secret
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: hospital-erp/backend
        property: encryption_key
    - secretKey: API_KEY
      remoteRef:
        key: hospital-erp/backend
        property: api_key
