apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yaml
  - cluster-secret-store.yaml
  - external-secret-database.yaml
  - external-secret-backend.yaml
  - external-secret-redis.yaml
